const ACCESS_HASH = '7ac147d99dabb1e993dd7afb7f11775f35d3dc1711569316b56e1a5e99946dc5';
const LS_STATE='siseExcel2026State', LS_STUDENT='siseExcel2026Student';
const initialState={theory:{filtros:false,avanzados:false,condicional:false,dinamicas:false},tips:false,games:{crossword:false,memory:false,wordsearch:false},quiz:false,quizScore:0};
let state=JSON.parse(localStorage.getItem(LS_STATE)||'null')||structuredClone(initialState);
let student=JSON.parse(localStorage.getItem(LS_STUDENT)||'null');
let activeTheory='filtros', activeGame='crossword', heroIndex=0, heroTimer;
// Normaliza estados creados con versiones anteriores de la app.
state.games=state.games||{};
if(typeof state.games.crossword!=='boolean')state.games.crossword=false;
if(typeof state.games.memory!=='boolean')state.games.memory=false;
if(typeof state.games.wordsearch!=='boolean')state.games.wordsearch=false;
if('mental' in state.games)delete state.games.mental;

const images=Array.from({length:10},(_,i)=>`assets/excel-${String(i+1).padStart(2,'0')}.png`);
const theoryData={
  filtros:{title:'Filtros',image:'assets/excel-01.png',lead:'Los filtros permiten mostrar únicamente los registros que cumplen una condición sin eliminar el resto de la base.',bullets:['Funcionan mejor cuando la base tiene encabezados claros y una fila por registro.','Puedes filtrar por texto, número, fecha, color o valores seleccionados.','Son ideales para búsquedas rápidas y análisis exploratorio.'],steps:['Selecciona una celda de la base.','Ve a Datos → Filtro o usa Ctrl + Shift + L.','Abre el desplegable de la columna.','Define el criterio y revisa los registros visibles.'],demo:{headers:['Producto','Región','Ventas','Fecha'],rows:[['Laptop','Norte','S/ 4,800','08/09/2026'],['Monitor','Sur','S/ 2,150','09/09/2026'],['Teclado','Norte','S/ 780','10/09/2026']],highlight:0},note:'Ejemplo: mostrar solo Región = Norte y luego ordenar Ventas de mayor a menor.'},
  avanzados:{title:'Filtros avanzados',image:'assets/excel-02.png',lead:'El filtro avanzado usa un rango de criterios separado para combinar condiciones y extraer resultados más específicos.',bullets:['Permite aplicar criterios con lógica AND y OR.','Puede filtrar la lista en el mismo lugar o copiar el resultado a otra zona.','Los encabezados del rango de criterios deben coincidir con los de la base.'],steps:['Crea un rango de criterios con encabezados idénticos.','Escribe las condiciones: misma fila = AND; filas distintas = OR.','Ve a Datos → Avanzadas.','Define rango de lista, rango de criterios y destino.'],demo:{headers:['Región','Ventas','Responsable','Resultado'],rows:[['Norte','>3000','Ana','Cumple AND'],['Sur','>5000','Luis','Alternativa OR'],['Norte','>3000','Ana','Filtrar/copy']],highlight:2},note:'Ejemplo: Región = Norte Y Ventas > 3000; o bien otra fila de criterios para una alternativa OR.'},
  condicional:{title:'Formato condicional',image:'assets/excel-04.png',lead:'El formato condicional cambia automáticamente la apariencia de las celdas cuando se cumple una regla.',bullets:['Ayuda a detectar valores altos, bajos, duplicados y tendencias.','Puede usar escalas de color, barras de datos, conjuntos de iconos o fórmulas.','Debe responder a un propósito de análisis, no solo decorar la hoja.'],steps:['Selecciona el rango de datos.','Inicio → Formato condicional.','Elige una regla y define el criterio.','Verifica que el formato destaque realmente lo importante.'],demo:{headers:['Responsable','Ventas','Meta','Estado'],rows:[['Ana','S/ 8,200','S/ 7,000','SUPERADA'],['Luis','S/ 5,100','S/ 7,000','PENDIENTE'],['María','S/ 7,600','S/ 7,000','SUPERADA']],highlight:0},note:'Ejemplo: resaltar en verde ventas ≥ meta y en rojo los resultados que requieren atención.'},
  dinamicas:{title:'Tablas dinámicas',image:'assets/excel-07.png',lead:'Una tabla dinámica resume grandes conjuntos de datos y permite analizarlos por categoría, periodo o responsable.',bullets:['Organiza campos en Filas, Columnas, Valores y Filtros.','Puede resumir con suma, conteo, promedio, máximo, mínimo y otros cálculos.','Es clave interpretar el resultado y formular conclusiones sustentadas.'],steps:['Selecciona la base organizada.','Insertar → Tabla dinámica.','Arrastra campos a Filas, Columnas, Valores y Filtros.','Analiza el resumen y formula una recomendación basada en evidencia.'],demo:{headers:['Región','Suma de Ventas','% Total','Lectura'],rows:[['Norte','S/ 18,300','42%','Mayor aporte'],['Sur','S/ 14,250','33%','Segundo aporte'],['Este','S/ 10,900','25%','Oportunidad']],highlight:0},note:'Ejemplo: resumir ventas por región y responsable para decidir dónde priorizar acciones.'}
};
const tips=[
  ['Ctrl + Shift + L','Activar o desactivar filtros en una tabla o rango.'],['Ctrl + T','Convertir un rango en tabla de Excel.'],['Alt + ↓','Abrir la lista desplegable de una celda o filtro.'],['Ctrl + Espacio','Seleccionar toda la columna activa.'],['Shift + Espacio','Seleccionar toda la fila activa.'],['Alt + N + V','Acceso por teclado para insertar una tabla dinámica.'],['Ctrl + Z','Deshacer la última acción.'],['Ctrl + 1','Abrir el cuadro Formato de celdas.'],['Ctrl + F','Buscar rápidamente datos o texto.']
];
const quizQuestions=[
  {q:'¿Qué herramienta usarías para mostrar solo los registros de una región sin borrar los demás?',o:['Formato condicional','Filtro','Tabla dinámica','Buscar y reemplazar'],a:1,e:'El filtro oculta temporalmente los registros que no cumplen el criterio.'},
  {q:'En un filtro avanzado, ¿qué significa colocar dos criterios en la misma fila del rango de criterios?',o:['Lógica OR','Lógica AND','Sin criterio','Orden descendente'],a:1,e:'Los criterios ubicados en la misma fila se combinan como AND.'},
  {q:'¿Cuál es un uso apropiado del formato condicional?',o:['Eliminar duplicados automáticamente','Resaltar ventas inferiores a la meta','Crear un correo','Cambiar el nombre del libro'],a:1,e:'El formato condicional es ideal para alertas, tendencias y valores relevantes.'},
  {q:'¿Cuál de estas áreas pertenece a una tabla dinámica?',o:['Filas','Pincel','Márgenes','Ortografía'],a:0,e:'Las tablas dinámicas utilizan Filas, Columnas, Valores y Filtros.'},
  {q:'Antes de analizar una base de datos, lo más importante es:',o:['Agregar muchos colores','Organizar encabezados, registros y tipos de datos','Insertar imágenes','Ocultar todas las columnas'],a:1,e:'Una estructura consistente es la base para aplicar filtros y resúmenes correctamente.'},
  {q:'¿Qué atajo activa o desactiva filtros?',o:['Ctrl + P','Ctrl + Shift + L','Ctrl + B','Alt + F4'],a:1,e:'Ctrl + Shift + L alterna los filtros en Excel.'},
  {q:'¿Para qué sirve principalmente una tabla dinámica?',o:['Dibujar formas','Resumir y reorganizar datos para analizarlos','Enviar correos','Proteger Windows'],a:1,e:'Su fortaleza es sintetizar datos por categorías, periodos y responsables.'},
  {q:'Si una IA propone una conclusión que contradice los datos de Excel, ¿qué debes hacer?',o:['Aceptar la IA sin revisar','Eliminar la base','Contrastar y verificar con los datos','Cambiar los datos'],a:2,e:'La sesión enfatiza usar IA de forma crítica y verificar coherencia con la evidencia.'},
  {q:'En un filtro avanzado, ¿por qué deben coincidir los encabezados del rango de criterios?',o:['Para que Excel relacione correctamente cada criterio con su campo','Solo por estética','Para cambiar el color','No deben coincidir'],a:0,e:'Excel necesita reconocer a qué campo corresponde cada condición.'},
  {q:'Después de obtener un resumen con tabla dinámica, ¿qué sigue según el enfoque de la sesión?',o:['Ignorarlo','Interpretar resultados y sustentar una decisión','Cerrar Excel','Copiar todo a Word sin revisar'],a:1,e:'El objetivo final es interpretar la información y formular conclusiones y una recomendación sustentada.'}
];

function saveState(){localStorage.setItem(LS_STATE,JSON.stringify(state));updateProgress();}
function completedCount(){return Object.values(state.theory).filter(Boolean).length+(state.tips?1:0)+Object.values(state.games).filter(Boolean).length+(state.quiz?1:0)}
function updateProgress(){const pct=Math.round(completedCount()/9*100);document.querySelector('#sidebarPct').textContent=pct+'%';document.querySelector('#topPct').textContent=pct+'%';document.querySelector('#sidebarBar').style.width=pct+'%';document.querySelector('#sidebarStatus').textContent=pct===100?'¡Ruta completada!':`${completedCount()} de 9 actividades`;renderDiplomaState();}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}

function fallbackSha256(ascii){function rightRotate(v,a){return(v>>>a)|(v<<(32-a))}let mathPow=Math.pow,maxWord=mathPow(2,32),lengthProperty='length',i,j,result='',words=[],asciiBitLength=ascii[lengthProperty]*8,hash=fallbackSha256.h=fallbackSha256.h||[],k=fallbackSha256.k=fallbackSha256.k||[],primeCounter=k[lengthProperty],isComposite={};for(let candidate=2;primeCounter<64;candidate++){if(!isComposite[candidate]){for(i=0;i<313;i+=candidate)isComposite[i]=candidate;hash[primeCounter]=(mathPow(candidate,.5)*maxWord)|0;k[primeCounter++]=(mathPow(candidate,1/3)*maxWord)|0}}ascii+='\x80';while(ascii[lengthProperty]%64-56)ascii+='\x00';for(i=0;i<ascii[lengthProperty];i++){j=ascii.charCodeAt(i);if(j>>8)return;words[i>>2]|=j<<((3-i)%4)*8}words[words[lengthProperty]]=(asciiBitLength/maxWord)|0;words[words[lengthProperty]]=asciiBitLength;for(j=0;j<words[lengthProperty];){let w=words.slice(j,j+=16),oldHash=hash;hash=hash.slice(0,8);for(i=0;i<64;i++){let i2=i+j,w15=w[i-15],w2=w[i-2],a=hash[0],e=hash[4],temp1=hash[7]+(rightRotate(e,6)^rightRotate(e,11)^rightRotate(e,25))+((e&hash[5])^((~e)&hash[6]))+k[i]+(w[i]=(i<16)?w[i]:(w[i-16]+(rightRotate(w15,7)^rightRotate(w15,18)^(w15>>>3))+w[i-7]+(rightRotate(w2,17)^rightRotate(w2,19)^(w2>>>10)))|0),temp2=(rightRotate(a,2)^rightRotate(a,13)^rightRotate(a,22))+((a&hash[1])^(a&hash[2])^(hash[1]&hash[2]));hash=[(temp1+temp2)|0].concat(hash);hash[4]=(hash[4]+temp1)|0}for(i=0;i<8;i++)hash[i]=(hash[i]+oldHash[i])|0}for(i=0;i<8;i++)for(j=3;j+1;j--){let b=(hash[i]>>(j*8))&255;result+=(b<16?0:'')+b.toString(16)}return result}
async function sha256(text){if(window.crypto?.subtle){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}return fallbackSha256(text)}

function initAuth(){const overlay=document.querySelector('#authOverlay');if(student){overlay.style.display='none';setStudentUI()}document.querySelector('#togglePassword').onclick=()=>{const i=document.querySelector('#accessKey');i.type=i.type==='password'?'text':'password'};document.querySelector('#authForm').addEventListener('submit',async e=>{e.preventDefault();const name=document.querySelector('#studentName').value.trim(),email=document.querySelector('#studentEmail').value.trim(),key=document.querySelector('#accessKey').value;const error=document.querySelector('#authError');error.textContent='Validando acceso…';const hash=await sha256(key);if(hash!==ACCESS_HASH){error.textContent='Clave incorrecta. Verifica la clave proporcionada por tu docente.';return}student={name,email};localStorage.setItem(LS_STUDENT,JSON.stringify(student));error.textContent='';overlay.style.display='none';setStudentUI();toast(`¡Bienvenido(a), ${name.split(' ')[0]}! Tu ruta de Excel comienza ahora.`)});document.querySelector('#logoutBtn').onclick=()=>{localStorage.removeItem(LS_STUDENT);location.reload()}}
function setStudentUI(){if(!student)return;const first=student.name.split(/\s+/)[0];document.querySelector('#studentChipName').textContent=first;document.querySelector('#avatar').textContent=(student.name.match(/\b\w/g)||['E']).slice(0,2).join('').toUpperCase();}

function navigate(id){document.querySelectorAll('.page-section').forEach(s=>s.classList.toggle('active-section',s.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.target===id));document.querySelector('#sidebar').classList.remove('open');document.querySelector('#mobileScrim').classList.remove('show');window.scrollTo({top:0,behavior:'smooth'});if(id==='teoria')renderTheory(activeTheory);if(id==='juegos')renderGame(activeGame);if(id==='quiz')renderQuiz();if(id==='diploma')renderDiplomaState()}
function initNav(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.target));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.topic)activeTheory=b.dataset.topic;navigate(b.dataset.go)});const btn=document.querySelector('#mobileMenuBtn'),side=document.querySelector('#sidebar'),scrim=document.querySelector('#mobileScrim');btn.onclick=()=>{side.classList.toggle('open');scrim.classList.toggle('show')};scrim.onclick=()=>{side.classList.remove('open');scrim.classList.remove('show')}}

function initHero(){const img=document.querySelector('#heroImage'),dots=document.querySelector('#heroDots'),gallery=document.querySelector('#galleryStrip');images.forEach((src,i)=>{const d=document.createElement('button');d.className=i===0?'active':'';d.setAttribute('aria-label',`Imagen ${i+1}`);d.onclick=()=>setHero(i);dots.append(d);const g=new Image();g.src=src;g.alt=`Escena de aprendizaje de Excel ${i+1}`;gallery.append(g)});function setHero(i){heroIndex=i;img.style.opacity=0;setTimeout(()=>{img.src=images[i];img.style.opacity=1},160);[...dots.children].forEach((d,n)=>d.classList.toggle('active',n===i));clearInterval(heroTimer);heroTimer=setInterval(()=>setHero((heroIndex+1)%images.length),5000)}window.setHero=setHero;heroTimer=setInterval(()=>setHero((heroIndex+1)%images.length),5000)}

function renderTheory(key){activeTheory=key;document.querySelectorAll('[data-theory]').forEach(b=>b.classList.toggle('active',b.dataset.theory===key));const d=theoryData[key],done=state.theory[key];const rows=d.demo.rows.map((r,i)=>`<tr class="${i===d.demo.highlight?'highlight':''}">${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('');document.querySelector('#theoryContent').innerHTML=`<article class="theory-panel"><div class="theory-top"><div class="theory-copy"><span class="kicker">HERRAMIENTA DE EXCEL</span><h2>${d.title}</h2><p>${d.lead}</p><ul>${d.bullets.map(x=>`<li>${x}</li>`).join('')}</ul><div class="quote-box">${d.note}</div></div><div class="theory-image"><img src="${d.image}" alt="${d.title} en un laboratorio de Excel"></div></div><div class="steps-grid">${d.steps.map((s,i)=>`<div class="step-card"><b>${i+1}</b>${s}</div>`).join('')}</div><div class="excel-demo"><div class="excel-demo-header">Ejemplo guiado · vista conceptual de una hoja de Excel</div><table class="excel-table"><thead><tr>${d.demo.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><div class="theory-complete"><button id="completeTheoryBtn" class="btn ${done?'btn-light':'btn-primary'}" ${done?'disabled':''}>${done?'Lección completada ✓':'Marcar lección como completada'}</button>${done?'<span class="done-pill">Progreso guardado</span>':''}</div></article>`;document.querySelector('#completeTheoryBtn').onclick=()=>{state.theory[key]=true;saveState();toast(`¡Excelente! Completaste ${d.title}.`);renderTheory(key)}}
function initTheory(){document.querySelectorAll('[data-theory]').forEach(b=>b.onclick=()=>renderTheory(b.dataset.theory));renderTheory(activeTheory)}

function initTips(){const grid=document.querySelector('#tipGrid');tips.forEach(([k,t])=>{const c=document.createElement('button');c.className='tip-card';c.innerHTML=`<kbd>${k}</kbd><h3>${t}</h3><p>Haz clic para marcar este atajo como revisado.</p>`;c.onclick=()=>c.classList.toggle('clicked');grid.append(c)});const b=document.querySelector('#completeTipsBtn');const refresh=()=>{b.disabled=state.tips;b.textContent=state.tips?'Tips + IA completados ✓':'Marcar Tips + IA como completados ✓'};b.onclick=()=>{state.tips=true;saveState();refresh();toast('¡Atajos dominados! Ya sabes trabajar más rápido y verificar mejor.')};refresh()}

const cwWords=[
 {answer:'FILTRO',row:5,col:3,dir:'H',clue:'Herramienta que muestra solo los registros que cumplen una condición.'},
 {answer:'DATOS',row:3,col:6,dir:'V',clue:'Información organizada que Excel permite analizar.'},
 {answer:'TABLA',row:4,col:5,dir:'H',clue:'Estructura de filas y columnas con encabezados.'},
 {answer:'CAMPO',row:3,col:9,dir:'V',clue:'Columna o atributo usado en una tabla dinámica.'},
 {answer:'RANGO',row:5,col:7,dir:'V',clue:'Conjunto de celdas seleccionado en una hoja.'}
];
function crosswordCellMap(){
  const map=new Map();
  cwWords.forEach((w,wi)=>[...w.answer].forEach((ch,i)=>{
    const r=w.row+(w.dir==='V'?i:0),c=w.col+(w.dir==='H'?i:0),key=`${r}-${c}`;
    if(!map.has(key))map.set(key,{r,c,ch,words:[]});
    const cell=map.get(key);
    if(cell.ch!==ch)throw new Error(`Crucigrama inválido: conflicto en ${key}`);
    cell.words.push(wi);
  }));
  return map;
}
function renderCrossword(){
  const cellMap=crosswordCellMap(),starts=new Map();
  cwWords.forEach((w,wi)=>{const key=`${w.row}-${w.col}`;if(!starts.has(key))starts.set(key,[]);starts.get(key).push(wi+1)});
  let cells='';
  for(let r=1;r<=10;r++)for(let c=1;c<=12;c++){
    const x=cellMap.get(`${r}-${c}`);if(!x)continue;
    const nums=starts.get(`${r}-${c}`)||[];
    cells+=`<label class="cw-wrap" style="grid-row:${r};grid-column:${c}">${nums.length?`<span class="cw-number">${nums.join('/')}</span>`:''}<input maxlength="1" inputmode="text" autocomplete="off" class="cw-cell" data-key="${r}-${c}" data-words="${x.words.join(',')}" aria-label="Celda crucigrama fila ${r} columna ${c}"></label>`;
  }
  return `<div class="game-shell"><div class="game-head"><div><h2>Crucigrama de Excel</h2><p>Selecciona una pista y escribe la respuesta en la cuadrícula. Cada letra se valida en tiempo real.</p></div><span id="cwBadge" class="game-badge">0 / ${cwWords.length}</span></div><div class="crossword-layout"><div><div class="crossword-grid">${cells}</div><div class="cw-actions"><button id="cwReset" class="btn btn-light" type="button">Reiniciar crucigrama</button><span id="cwHint">Selecciona una pista para comenzar.</span></div></div><div class="clue-list">${cwWords.map((w,i)=>`<button type="button" class="clue" id="clue-${i}" data-cw-word="${i}"><strong>${i+1}. ${w.dir==='H'?'Horizontal':'Vertical'}</strong><br>${w.clue}<small>${w.answer.length} letras</small></button>`).join('')}</div></div></div>`;
}
function bindCrossword(){
  const cellMap=crosswordCellMap(),inputs=[...document.querySelectorAll('.cw-cell')];
  let activeWord=0;
  function wordCells(wi){const w=cwWords[wi];return [...w.answer].map((_,i)=>document.querySelector(`[data-key="${w.row+(w.dir==='V'?i:0)}-${w.col+(w.dir==='H'?i:0)}"]`));}
  function selectWord(wi,focus=true){activeWord=wi;document.querySelectorAll('.clue').forEach((x,i)=>x.classList.toggle('active-clue',i===wi));inputs.forEach(x=>x.closest('.cw-wrap').classList.remove('active-word'));wordCells(wi).forEach(x=>x&&x.closest('.cw-wrap').classList.add('active-word'));document.querySelector('#cwHint').textContent=`Pista ${wi+1}: ${cwWords[wi].dir==='H'?'Horizontal':'Vertical'} · ${cwWords[wi].answer.length} letras`;if(focus){const target=wordCells(wi).find(x=>!x.value)||wordCells(wi)[0];target?.focus()}}
  function checkCW(){
    inputs.forEach(el=>{const expected=cellMap.get(el.dataset.key).ch;el.classList.toggle('correct',!!el.value&&el.value===expected);el.classList.toggle('wrong',!!el.value&&el.value!==expected)});
    let correct=0;
    cwWords.forEach((w,wi)=>{const ok=wordCells(wi).every((el,i)=>el&&el.value===w.answer[i]);document.querySelector(`#clue-${wi}`).classList.toggle('done-pill',ok);if(ok)correct++});
    document.querySelector('#cwBadge').textContent=`${correct} / ${cwWords.length}`;
    if(correct===cwWords.length&&!state.games.crossword){state.games.crossword=true;saveState();toast('¡Crucigrama completado! Todas las respuestas son correctas.')}
  }
  document.querySelectorAll('[data-cw-word]').forEach(btn=>btn.onclick=()=>selectWord(+btn.dataset.cwWord));
  inputs.forEach(inp=>{
    inp.addEventListener('focus',()=>{const ws=inp.dataset.words.split(',').map(Number);if(!ws.includes(activeWord))selectWord(ws[0],false)});
    inp.addEventListener('input',()=>{inp.value=inp.value.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-ZÑ]/g,'').slice(0,1);checkCW();if(inp.value){const seq=wordCells(activeWord),i=seq.indexOf(inp);if(i>=0&&seq[i+1])seq[i+1].focus()}});
    inp.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!inp.value){const seq=wordCells(activeWord),i=seq.indexOf(inp);if(i>0){seq[i-1].value='';seq[i-1].focus();checkCW()}}});
  });
  document.querySelector('#cwReset').onclick=()=>{inputs.forEach(x=>{x.value='';x.classList.remove('correct','wrong')});document.querySelectorAll('.clue').forEach(x=>x.classList.remove('done-pill'));document.querySelector('#cwBadge').textContent=`0 / ${cwWords.length}`;selectWord(0,false);toast('Crucigrama reiniciado.')};
  selectWord(0,false);checkCW();
}

const memoryPairs=[
 {id:'filtro',icon:'🔎',label:'Filtro'},
 {id:'avanzado',icon:'⚙️',label:'Filtro avanzado'},
 {id:'condicional',icon:'🎨',label:'Formato condicional'},
 {id:'dinamica',icon:'📊',label:'Tabla dinámica'},
 {id:'datos',icon:'🧾',label:'Datos'},
 {id:'rango',icon:'▦',label:'Rango'},
 {id:'criterio',icon:'✅',label:'Criterio'},
 {id:'campo',icon:'📋',label:'Campo'}
];
function shuffleMemoryCards(){const cards=memoryPairs.flatMap((p,i)=>[{...p,uid:`${p.id}-a`},{...p,uid:`${p.id}-b`}]);for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
function renderMemory(){
  const cards=shuffleMemoryCards();
  return `<div class="game-shell"><div class="game-head"><div><h2>Juego de memoria: pares de Excel</h2><p>Voltea dos tarjetas y encuentra los 8 pares de conceptos. Las parejas correctas quedan visibles.</p></div><span id="memoryBadge" class="game-badge">0 / 8 pares</span></div><div class="memory-toolbar"><span id="memoryMoves">0 movimientos</span><button id="memoryReset" class="btn btn-light" type="button">Mezclar y reiniciar</button></div><div class="memory-grid">${cards.map((c,i)=>`<button type="button" class="memory-card" data-index="${i}" data-pair="${c.id}" aria-label="Tarjeta de memoria ${i+1}"><span class="memory-card-inner"><span class="memory-back"><b>X</b><small>Excel</small></span><span class="memory-front"><b>${c.icon}</b><small>${c.label}</small></span></span></button>`).join('')}</div><p id="memoryNote" class="selection-note">Encuentra dos tarjetas iguales para formar un par.</p></div>`;
}
function bindMemory(){
  const cards=[...document.querySelectorAll('.memory-card')];let first=null,second=null,locked=false,moves=0,matched=0;
  function resetBoard(){document.querySelector('#gameArea').innerHTML=renderMemory();bindMemory()}
  document.querySelector('#memoryReset').onclick=resetBoard;
  cards.forEach(card=>card.onclick=()=>{
    if(locked||card.classList.contains('matched')||card===first)return;
    card.classList.add('flipped');
    if(!first){first=card;document.querySelector('#memoryNote').textContent='Elige una segunda tarjeta.';return}
    second=card;moves++;document.querySelector('#memoryMoves').textContent=`${moves} movimiento${moves===1?'':'s'}`;
    if(first.dataset.pair===second.dataset.pair){
      first.classList.add('matched');second.classList.add('matched');matched++;document.querySelector('#memoryBadge').textContent=`${matched} / 8 pares`;document.querySelector('#memoryNote').textContent='¡Pareja encontrada! Continúa.';first=second=null;
      if(matched===memoryPairs.length&&!state.games.memory){state.games.memory=true;saveState();toast('¡Juego de memoria completado! Encontraste los 8 pares de Excel.')}
    }else{
      locked=true;document.querySelector('#memoryNote').textContent='No coinciden. Memoriza su posición e inténtalo otra vez.';setTimeout(()=>{first.classList.remove('flipped');second.classList.remove('flipped');first=second=null;locked=false},850)
    }
  })
}

const wsWords=['FILTRO','AVANZADO','FORMATO','CONDICIONAL','TABLA','DINAMICA','DATOS','CRITERIO','CAMPO','EXCEL'];
let wsData=null;
function seeded(seed=2026){return()=>{seed=(seed*9301+49297)%233280;return seed/233280}}
function buildWordSearch(){const size=15,grid=Array.from({length:size},()=>Array(size).fill('')),placed=[],rand=seeded(14092026),dirs=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]];for(const word of wsWords){let ok=false;for(let tries=0;tries<800&&!ok;tries++){const [dr,dc]=dirs[Math.floor(rand()*dirs.length)],r=Math.floor(rand()*size),c=Math.floor(rand()*size),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||er>=size||ec<0||ec>=size)continue;let fits=true;for(let i=0;i<word.length;i++){const ch=grid[r+dr*i][c+dc*i];if(ch&&ch!==word[i]){fits=false;break}}if(!fits)continue;const cells=[];for(let i=0;i<word.length;i++){grid[r+dr*i][c+dc*i]=word[i];cells.push([r+dr*i,c+dc*i])}placed.push({word,cells});ok=true}if(!ok)throw new Error('No se pudo crear la sopa de letras')}const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ',r2=seeded(9876);for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!grid[r][c])grid[r][c]=letters[Math.floor(r2()*letters.length)];return{size,grid,placed}}
function renderWordSearch(){if(!wsData)wsData=buildWordSearch();return `<div class="game-shell"><div class="game-head"><div><h2>Sopa de letras de Excel</h2><p>Encuentra exactamente 10 palabras. Haz clic en la primera y en la última letra de cada palabra.</p></div><span id="wsBadge" class="game-badge">0 / 10</span></div><div class="wordsearch-layout"><div class="word-grid">${wsData.grid.flatMap((row,r)=>row.map((ch,c)=>`<button class="ws-cell" data-r="${r}" data-c="${c}">${ch}</button>`)).join('')}</div><div><div class="word-list">${wsWords.map(w=>`<span class="word-pill" data-word="${w}">${w}</span>`).join('')}</div><p class="selection-note" id="wsNote">Selecciona la primera letra de una palabra.</p></div></div></div>`}
function bindWordSearch(){let start=null,found=new Set();const cells=[...document.querySelectorAll('.ws-cell')];function path(a,b){const dr=b.r-a.r,dc=b.c-a.c;if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc)))return[];const len=Math.max(Math.abs(dr),Math.abs(dc))+1,sr=Math.sign(dr),sc=Math.sign(dc);return Array.from({length:len},(_,i)=>[a.r+sr*i,a.c+sc*i])}cells.forEach(cell=>cell.onclick=()=>{const p={r:+cell.dataset.r,c:+cell.dataset.c};if(!start){start=p;cell.classList.add('selected');document.querySelector('#wsNote').textContent='Ahora selecciona la última letra.';return}cells.forEach(x=>x.classList.remove('selected'));const pp=path(start,p),text=pp.map(([r,c])=>wsData.grid[r][c]).join(''),match=wsWords.find(w=>w===text||w===[...text].reverse().join(''));if(match&&!found.has(match)){found.add(match);pp.forEach(([r,c])=>document.querySelector(`.ws-cell[data-r="${r}"][data-c="${c}"]`).classList.add('found'));document.querySelector(`.word-pill[data-word="${match}"]`).classList.add('found');document.querySelector('#wsNote').textContent=`¡Encontraste ${match}! Busca otra palabra.`}else document.querySelector('#wsNote').textContent='Esa selección no corresponde a una palabra pendiente. Intenta otra vez.';start=null;document.querySelector('#wsBadge').textContent=`${found.size} / 10`;if(found.size===10&&!state.games.wordsearch){state.games.wordsearch=true;saveState();toast('¡Sopa de letras completada! Encontraste las 10 palabras de Excel.')}})}
function renderGame(key){activeGame=key;document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===key));const area=document.querySelector('#gameArea');if(key==='crossword'){area.innerHTML=renderCrossword();bindCrossword()}else if(key==='memory'){area.innerHTML=renderMemory();bindMemory()}else{area.innerHTML=renderWordSearch();bindWordSearch()}}
function initGames(){document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>renderGame(b.dataset.game));renderGame(activeGame)}

let quizIndex=0,quizCorrect=0,quizAnswered=false;
function renderQuiz(){const card=document.querySelector('#quizCard');if(state.quiz&&quizIndex===0){card.innerHTML=`<div class="quiz-question">Cuestionario completado</div><p>Tu último resultado fue <strong>${state.quizScore}/10</strong>. Puedes repetirlo para reforzar tus conocimientos.</p><button id="retryQuiz" class="btn btn-primary">Repetir cuestionario</button>`;document.querySelector('#quizCount').textContent='10 de 10 preguntas respondidas';document.querySelector('#quizScore').textContent=`${state.quizScore} correctas`;document.querySelector('#quizBar').style.width='100%';document.querySelector('#retryQuiz').onclick=()=>{quizIndex=0;quizCorrect=0;quizAnswered=false;state.quiz=false;saveState();renderQuizQuestion()};return}renderQuizQuestion()}
function renderQuizQuestion(){const q=quizQuestions[quizIndex],card=document.querySelector('#quizCard');document.querySelector('#quizCount').textContent=`Pregunta ${quizIndex+1} de 10`;document.querySelector('#quizScore').textContent=`${quizCorrect} correctas`;document.querySelector('#quizBar').style.width=`${quizIndex*10}%`;quizAnswered=false;card.innerHTML=`<div class="quiz-question">${q.q}</div><div class="quiz-options">${q.o.map((o,i)=>`<button class="quiz-option" data-opt="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="quizFeedback"></div>`;card.querySelectorAll('.quiz-option').forEach(btn=>btn.onclick=()=>answerQuiz(+btn.dataset.opt))}
function answerQuiz(ans){if(quizAnswered)return;quizAnswered=true;const q=quizQuestions[quizIndex],ok=ans===q.a;if(ok)quizCorrect++;document.querySelectorAll('.quiz-option').forEach((b,i)=>{b.disabled=true;if(i===q.a)b.classList.add('correct');else if(i===ans)b.classList.add('wrong')});document.querySelector('#quizFeedback').innerHTML=`<div class="feedback-box ${ok?'good':'bad'}"><strong>${ok?'¡Correcto!':'Respuesta incorrecta.'}</strong> ${q.e}</div><button id="nextQuiz" class="btn btn-primary quiz-next">${quizIndex===9?'Finalizar cuestionario':'Siguiente pregunta →'}</button>`;document.querySelector('#quizScore').textContent=`${quizCorrect} correctas`;document.querySelector('#nextQuiz').onclick=()=>{if(quizIndex<9){quizIndex++;renderQuizQuestion()}else{state.quiz=true;state.quizScore=quizCorrect;saveState();document.querySelector('#quizBar').style.width='100%';toast(`¡Cuestionario completado! Resultado: ${quizCorrect}/10.`);quizIndex=0;renderQuiz()}}}

function allDone(){return completedCount()===9}
function requirementRows(){return [
 ['Teoría: Filtros',state.theory.filtros],['Teoría: Filtros avanzados',state.theory.avanzados],['Teoría: Formato condicional',state.theory.condicional],['Teoría: Tablas dinámicas',state.theory.dinamicas],['Tips + uso crítico de IA',state.tips],['Juego: Crucigrama',state.games.crossword],['Juego: Memoria',state.games.memory],['Juego: Sopa de letras',state.games.wordsearch],['Cuestionario de 10 preguntas',state.quiz]
]}
function renderDiplomaState(){const locked=document.querySelector('#diplomaLocked'),ready=document.querySelector('#diplomaReady');if(!locked||!ready)return;document.querySelector('#requirementsList').innerHTML=requirementRows().map(([n,d])=>`<div class="req ${d?'done':''}"><span>${d?'✓':'○'}</span><span>${n}</span></div>`).join('');document.querySelector('#lockedText').textContent=`Llevas ${completedCount()} de 9 actividades obligatorias.`;if(allDone()&&student){locked.classList.add('hidden');ready.classList.remove('hidden');document.querySelector('#diplomaName').textContent=student.name;document.querySelector('#diplomaEmail').textContent=student.email;document.querySelector('#diplomaDate').textContent=new Intl.DateTimeFormat('es-PE',{dateStyle:'long'}).format(new Date());document.querySelector('#diplomaScore').textContent=`${state.quizScore}/10`}else{locked.classList.remove('hidden');ready.classList.add('hidden')}}
function wrapCanvasText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='',lines=[];for(const w of words){const test=line+w+' ';if(ctx.measureText(test).width>maxWidth&&line){lines.push(line.trim());line=w+' '}else line=test}if(line)lines.push(line.trim());lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));return y+lines.length*lineHeight}
async function makeDiplomaCanvas(){const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1131;const c=canvas.getContext('2d');c.fillStyle='#ffffff';c.fillRect(0,0,1600,1131);c.strokeStyle='#107c41';c.lineWidth=20;c.strokeRect(34,34,1532,1063);c.strokeStyle='#75c99c';c.lineWidth=4;c.strokeRect(58,58,1484,1015);c.fillStyle='#eaf7ef';c.beginPath();c.arc(110,110,145,0,Math.PI*2);c.fill();c.beginPath();c.arc(1490,1020,190,0,Math.PI*2);c.fill();const logo=new Image();logo.src='assets/logo-sise.png';await logo.decode().catch(()=>{});c.drawImage(logo,90,85,240,95);c.fillStyle='#107c41';c.fillRect(1340,90,120,120);c.fillStyle='#fff';c.font='900 70px Arial';c.textAlign='center';c.fillText('X',1400,172);c.fillStyle='#107c41';c.font='800 26px Arial';c.letterSpacing='5px';c.fillText('DIPLOMA DE FINALIZACIÓN',800,220);c.fillStyle='#16283a';c.font='bold 48px Georgia';wrapCanvasText(c,'Microsoft Excel: Organización de Datos y Análisis Básico',800,310,1050,58);c.font='28px Arial';c.fillStyle='#53675c';c.fillText('Se otorga el presente reconocimiento a',800,455);c.font='bold 64px Georgia';c.fillStyle='#0b5d34';c.fillText(student.name,800,545);c.strokeStyle='#9bcab0';c.lineWidth=2;c.beginPath();c.moveTo(350,570);c.lineTo(1250,570);c.stroke();c.font='25px Arial';c.fillStyle='#53675c';c.fillText(student.email,800,615);c.font='25px Arial';c.fillStyle='#334e40';wrapCanvasText(c,'por completar las actividades de filtros, filtros avanzados, formato condicional, tablas dinámicas y análisis básico, interpretando resultados y verificando críticamente el apoyo de IA.',800,690,1130,38);c.font='bold 24px Arial';c.fillStyle='#107c41';c.fillText(`Fecha: ${new Intl.DateTimeFormat('es-PE',{dateStyle:'long'}).format(new Date())}`,520,830);c.fillText(`Cuestionario: ${state.quizScore}/10`,1080,830);c.strokeStyle='#60756a';c.lineWidth=2;c.beginPath();c.moveTo(230,955);c.lineTo(610,955);c.moveTo(990,955);c.lineTo(1370,955);c.stroke();c.fillStyle='#334e40';c.font='20px Arial';c.fillText('DÁVILA SALVADOR, Julio · Docente',420,990);c.fillText('Taller de Informática para la Empleabilidad',1180,990);c.beginPath();c.fillStyle='#d5ad35';c.arc(800,940,62,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='bold 22px Arial';c.fillText('SISE',800,935);c.font='18px Arial';c.fillText('2026',800,962);return canvas}
function base64Bytes(dataUrl){const b64=dataUrl.split(',')[1],bin=atob(b64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return arr}
function textBytes(s){return new TextEncoder().encode(s)}
function concatBytes(parts){const n=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(n);let p=0;parts.forEach(b=>{out.set(b,p);p+=b.length});return out}
function buildPdfFromJpeg(jpeg,width,height){const pageW=842,pageH=595;const objs=[];objs[1]=textBytes('<< /Type /Catalog /Pages 2 0 R >>');objs[2]=textBytes('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');objs[3]=textBytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`);objs[4]=concatBytes([textBytes(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,textBytes('\nendstream')]);const content=textBytes(`q\n${pageW} 0 0 ${pageH} 0 0 cm\n/Im0 Do\nQ`);objs[5]=concatBytes([textBytes(`<< /Length ${content.length} >>\nstream\n`),content,textBytes('\nendstream')]);let parts=[textBytes('%PDF-1.3\n%\xE2\xE3\xCF\xD3\n')],offsets=[0],pos=parts[0].length;for(let i=1;i<=5;i++){offsets[i]=pos;const ob=concatBytes([textBytes(`${i} 0 obj\n`),objs[i],textBytes('\nendobj\n')]);parts.push(ob);pos+=ob.length}const xref=pos;let table=`xref\n0 6\n0000000000 65535 f \n`;for(let i=1;i<=5;i++)table+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';parts.push(textBytes(table+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return concatBytes(parts)}
async function downloadDiploma(){if(!allDone())return;toast('Generando tu diploma PDF…');const canvas=await makeDiplomaCanvas(),jpeg=base64Bytes(canvas.toDataURL('image/jpeg',.95)),pdf=buildPdfFromJpeg(jpeg,canvas.width,canvas.height),blob=new Blob([pdf],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Diploma_SISE_Excel_${student.name.replace(/\s+/g,'_')}.pdf`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('¡Diploma generado! Excelente trabajo.')}
function initDiploma(){document.querySelector('#downloadDiplomaBtn').onclick=downloadDiploma;document.querySelector('#printDiplomaBtn').onclick=()=>window.print();renderDiplomaState()}

function init(){initAuth();initNav();initHero();initTheory();initTips();initGames();initDiploma();updateProgress()}
document.addEventListener('DOMContentLoaded',init);
